# For running the database and the application as whole
# This compose file runs the app in production, you cannot see live changes in the code
services:
  postgres:
    image: postgres:16.3
    container_name: roc8assignment_database
    environment:
      POSTGRES_DB: roc8assignment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 851bd86aae112e656b9b4ac0e5b06c73bb55c6335174e445d0e620d8a0d803d2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - assignment_pg_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d roc8assignment"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3434/api

    container_name: roc8assignment_client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      # since server and database are in same network in this file we are using port 5432 and host postgres. But if you are connecting outside with a db visualizer or any other tool you can use the port 5430 and host localhost
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=roc8assignment
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=851bd86aae112e656b9b4ac0e5b06c73bb55c6335174e445d0e620d8a0d803d2
      - PORT=3434
      # generate your own secret keys by using openssl rand -hex 32
      - JWT_ACCESS_SECRET_KEY=a80c8286a86ba69da390c64084d32ff7b1c32b17c78b926269eaf9e5c0aaca4a
      - JWT_REFRESH_SECRET_KEY=6f1348ec94e0270d036b43b096d187f77d24b34248d0ccd7ecf32a58c673fee1
      - CLIENT_URL=http://localhost:3000
      # set NODE_ENV_APP=production for production environent with https and using a database with ssl
      - NODE_ENV_APP=development
      # smtp credentials required for sending emails during signup, add your own smtp credentials
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USER=
      - SMTP_PASSWORD=
    container_name: roc8assignment_server
    ports:
      - "3434:3434"
    depends_on:
      - postgres

volumes:
  assignment_pg_data:
